# Generated by Django 5.1.2 on 2024-10-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_customuser_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propriedade', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('access_level', models.IntegerField(default=1)),
            ],
        ),
    ]
