# Generated by Django 5.1.2 on 2024-10-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_environmentaldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentaldata',
            old_name='access_level',
            new_name='required_access_level',
        ),
    ]
